version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "kdpisda"
  
  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "kdpisda"
  
  # Maintain dependencies for npm (documentation)
  - package-ecosystem: "npm"
    directory: "/documentations"
    schedule:
      interval: "weekly"
    reviewers:
      - "kdpisda"
    # Limit to documentation-related updates
    allow:
      - dependency-type: "all"