# Lightweight compose file specifically for testing
version: '3.8'

services:
  test-postgres:
    image: postgres:17-alpine
    container_name: django_rls_test_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_django_rls
      # Optimization for tests - faster but less durable
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums=off"
      POSTGRES_HOST_AUTH_METHOD: "trust"  # No password for local testing
    command: 
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "fsync=off"              # Faster for tests
      - "-c"
      - "synchronous_commit=off" # Faster for tests
      - "-c"
      - "full_page_writes=off"   # Faster for tests
      - "-c"
      - "checkpoint_segments=32"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    tmpfs:
      - /var/lib/postgresql/data  # Store data in memory for speed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 10
    restart: "no"