/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'installation',
    'quick-start',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/configuration',
        'guides/context',
        'guides/policies',
        'guides/middleware',
        'guides/management-commands',
        'guides/testing',
        'guides/migrating-from-0.4',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/basic-usage',
        'examples/tenant-based',
        'examples/user-based',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'category',
          label: 'Enterprise ERP System',
          items: [
            {
              type: 'autogenerated',
              dirName: 'tutorials/enterprise-erp',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/local_testing',
        'contributing/releasing',
        'contributing/pypi_setup',
      ],
    },
    'api-reference',
  ],
};

module.exports = sidebars;