name: Documentation Health Check

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check documentation site
        id: health
        run: |
          # Check if the site is accessible
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://django-rls.com)
          
          if [ "$RESPONSE" = "200" ]; then
            echo "✅ Documentation site is healthy"
            echo "status=healthy" >> $GITHUB_OUTPUT
          else
            echo "❌ Documentation site returned HTTP $RESPONSE"
            echo "status=unhealthy" >> $GITHUB_OUTPUT
            exit 1
          fi
      
      - name: Check critical pages
        if: steps.health.outputs.status == 'healthy'
        run: |
          # List of critical pages to check
          PAGES=(
            "https://django-rls.com/docs/intro"
            "https://django-rls.com/docs/installation"
            "https://django-rls.com/docs/quick-start"
            "https://django-rls.com/docs/api-reference"
          )
          
          for PAGE in "${PAGES[@]}"; do
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$PAGE")
            if [ "$RESPONSE" != "200" ]; then
              echo "❌ Page $PAGE returned HTTP $RESPONSE"
              exit 1
            fi
            echo "✅ Page $PAGE is accessible"
          done
      
      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Documentation Site Health Check Failed',
              body: `The documentation site health check has failed.
              
              **Site:** https://django-rls.com
              **Time:** ${new Date().toISOString()}
              **Workflow:** ${context.workflow}
              **Run:** ${context.runNumber}
              
              Please check the [workflow logs](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`,
              labels: ['documentation', 'urgent']
            });
            
            console.log(`Created issue #${issue.data.number}`);