name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm PyPI release'
        required: true
        default: 'no'

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'yes'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    
    - name: Get version
      id: version
      run: |
        VERSION=$(python -c "import sys; sys.path.insert(0, '.'); from django_rls.__version__ import __version__; print(__version__)")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Publishing version: $VERSION"
    
    - name: Build package
      run: |
        poetry build
    
    - name: Check package
      run: |
        pip install twine
        twine check dist/*
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        body: |
          ## Django-RLS v${{ steps.version.outputs.version }}
          
          Install from PyPI:
          ```bash
          pip install django-rls==${{ steps.version.outputs.version }}
          ```
          
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
        draft: false
        files: dist/*